/*
Coinbase Advanced Trading API

OpenAPI 3.x specification for Coinbase Adavanced Trading

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// GetExchangeRateResponse struct for GetExchangeRateResponse
type GetExchangeRateResponse struct {
	Data *GetExchangeRateResponseData `json:"data,omitempty"`
}

// NewGetExchangeRateResponse instantiates a new GetExchangeRateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetExchangeRateResponse() *GetExchangeRateResponse {
	this := GetExchangeRateResponse{}
	return &this
}

// NewGetExchangeRateResponseWithDefaults instantiates a new GetExchangeRateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetExchangeRateResponseWithDefaults() *GetExchangeRateResponse {
	this := GetExchangeRateResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetExchangeRateResponse) GetData() GetExchangeRateResponseData {
	if o == nil || isNil(o.Data) {
		var ret GetExchangeRateResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeRateResponse) GetDataOk() (*GetExchangeRateResponseData, bool) {
	if o == nil || isNil(o.Data) {
    return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetExchangeRateResponse) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetExchangeRateResponseData and assigns it to the Data field.
func (o *GetExchangeRateResponse) SetData(v GetExchangeRateResponseData) {
	o.Data = &v
}

func (o GetExchangeRateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetExchangeRateResponse struct {
	value *GetExchangeRateResponse
	isSet bool
}

func (v NullableGetExchangeRateResponse) Get() *GetExchangeRateResponse {
	return v.value
}

func (v *NullableGetExchangeRateResponse) Set(val *GetExchangeRateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetExchangeRateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetExchangeRateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetExchangeRateResponse(val *GetExchangeRateResponse) *NullableGetExchangeRateResponse {
	return &NullableGetExchangeRateResponse{value: val, isSet: true}
}

func (v NullableGetExchangeRateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetExchangeRateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


