/*
Coinbase Advanced Trading API

OpenAPI 3.x specification for Coinbase Adavanced Trading

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// CreateOrderRequestOrderConfigurationLimitLimitGtd struct for CreateOrderRequestOrderConfigurationLimitLimitGtd
type CreateOrderRequestOrderConfigurationLimitLimitGtd struct {
	BaseSize *string `json:"base_size,omitempty"`
	LimitPrice *string `json:"limit_price,omitempty"`
	EndTime *string `json:"end_time,omitempty"`
	PostOnly *bool `json:"post_only,omitempty"`
}

// NewCreateOrderRequestOrderConfigurationLimitLimitGtd instantiates a new CreateOrderRequestOrderConfigurationLimitLimitGtd object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestOrderConfigurationLimitLimitGtd() *CreateOrderRequestOrderConfigurationLimitLimitGtd {
	this := CreateOrderRequestOrderConfigurationLimitLimitGtd{}
	return &this
}

// NewCreateOrderRequestOrderConfigurationLimitLimitGtdWithDefaults instantiates a new CreateOrderRequestOrderConfigurationLimitLimitGtd object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestOrderConfigurationLimitLimitGtdWithDefaults() *CreateOrderRequestOrderConfigurationLimitLimitGtd {
	this := CreateOrderRequestOrderConfigurationLimitLimitGtd{}
	return &this
}

// GetBaseSize returns the BaseSize field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) GetBaseSize() string {
	if o == nil || isNil(o.BaseSize) {
		var ret string
		return ret
	}
	return *o.BaseSize
}

// GetBaseSizeOk returns a tuple with the BaseSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) GetBaseSizeOk() (*string, bool) {
	if o == nil || isNil(o.BaseSize) {
    return nil, false
	}
	return o.BaseSize, true
}

// HasBaseSize returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) HasBaseSize() bool {
	if o != nil && !isNil(o.BaseSize) {
		return true
	}

	return false
}

// SetBaseSize gets a reference to the given string and assigns it to the BaseSize field.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) SetBaseSize(v string) {
	o.BaseSize = &v
}

// GetLimitPrice returns the LimitPrice field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) GetLimitPrice() string {
	if o == nil || isNil(o.LimitPrice) {
		var ret string
		return ret
	}
	return *o.LimitPrice
}

// GetLimitPriceOk returns a tuple with the LimitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) GetLimitPriceOk() (*string, bool) {
	if o == nil || isNil(o.LimitPrice) {
    return nil, false
	}
	return o.LimitPrice, true
}

// HasLimitPrice returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) HasLimitPrice() bool {
	if o != nil && !isNil(o.LimitPrice) {
		return true
	}

	return false
}

// SetLimitPrice gets a reference to the given string and assigns it to the LimitPrice field.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) SetLimitPrice(v string) {
	o.LimitPrice = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) GetEndTime() string {
	if o == nil || isNil(o.EndTime) {
		var ret string
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) GetEndTimeOk() (*string, bool) {
	if o == nil || isNil(o.EndTime) {
    return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) HasEndTime() bool {
	if o != nil && !isNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given string and assigns it to the EndTime field.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) SetEndTime(v string) {
	o.EndTime = &v
}

// GetPostOnly returns the PostOnly field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) GetPostOnly() bool {
	if o == nil || isNil(o.PostOnly) {
		var ret bool
		return ret
	}
	return *o.PostOnly
}

// GetPostOnlyOk returns a tuple with the PostOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) GetPostOnlyOk() (*bool, bool) {
	if o == nil || isNil(o.PostOnly) {
    return nil, false
	}
	return o.PostOnly, true
}

// HasPostOnly returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) HasPostOnly() bool {
	if o != nil && !isNil(o.PostOnly) {
		return true
	}

	return false
}

// SetPostOnly gets a reference to the given bool and assigns it to the PostOnly field.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtd) SetPostOnly(v bool) {
	o.PostOnly = &v
}

func (o CreateOrderRequestOrderConfigurationLimitLimitGtd) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.BaseSize) {
		toSerialize["base_size"] = o.BaseSize
	}
	if !isNil(o.LimitPrice) {
		toSerialize["limit_price"] = o.LimitPrice
	}
	if !isNil(o.EndTime) {
		toSerialize["end_time"] = o.EndTime
	}
	if !isNil(o.PostOnly) {
		toSerialize["post_only"] = o.PostOnly
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrderRequestOrderConfigurationLimitLimitGtd struct {
	value *CreateOrderRequestOrderConfigurationLimitLimitGtd
	isSet bool
}

func (v NullableCreateOrderRequestOrderConfigurationLimitLimitGtd) Get() *CreateOrderRequestOrderConfigurationLimitLimitGtd {
	return v.value
}

func (v *NullableCreateOrderRequestOrderConfigurationLimitLimitGtd) Set(val *CreateOrderRequestOrderConfigurationLimitLimitGtd) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestOrderConfigurationLimitLimitGtd) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestOrderConfigurationLimitLimitGtd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestOrderConfigurationLimitLimitGtd(val *CreateOrderRequestOrderConfigurationLimitLimitGtd) *NullableCreateOrderRequestOrderConfigurationLimitLimitGtd {
	return &NullableCreateOrderRequestOrderConfigurationLimitLimitGtd{value: val, isSet: true}
}

func (v NullableCreateOrderRequestOrderConfigurationLimitLimitGtd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestOrderConfigurationLimitLimitGtd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


