/*
Coinbase Advanced Trading API

OpenAPI 3.x specification for Coinbase Adavanced Trading

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// CreateOrderRequestOrderConfigurationMarketMarketIoc struct for CreateOrderRequestOrderConfigurationMarketMarketIoc
type CreateOrderRequestOrderConfigurationMarketMarketIoc struct {
	QuoteSize *string `json:"quote_size,omitempty"`
	BaseSize *string `json:"base_size,omitempty"`
}

// NewCreateOrderRequestOrderConfigurationMarketMarketIoc instantiates a new CreateOrderRequestOrderConfigurationMarketMarketIoc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestOrderConfigurationMarketMarketIoc() *CreateOrderRequestOrderConfigurationMarketMarketIoc {
	this := CreateOrderRequestOrderConfigurationMarketMarketIoc{}
	return &this
}

// NewCreateOrderRequestOrderConfigurationMarketMarketIocWithDefaults instantiates a new CreateOrderRequestOrderConfigurationMarketMarketIoc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestOrderConfigurationMarketMarketIocWithDefaults() *CreateOrderRequestOrderConfigurationMarketMarketIoc {
	this := CreateOrderRequestOrderConfigurationMarketMarketIoc{}
	return &this
}

// GetQuoteSize returns the QuoteSize field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationMarketMarketIoc) GetQuoteSize() string {
	if o == nil || isNil(o.QuoteSize) {
		var ret string
		return ret
	}
	return *o.QuoteSize
}

// GetQuoteSizeOk returns a tuple with the QuoteSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationMarketMarketIoc) GetQuoteSizeOk() (*string, bool) {
	if o == nil || isNil(o.QuoteSize) {
    return nil, false
	}
	return o.QuoteSize, true
}

// HasQuoteSize returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationMarketMarketIoc) HasQuoteSize() bool {
	if o != nil && !isNil(o.QuoteSize) {
		return true
	}

	return false
}

// SetQuoteSize gets a reference to the given string and assigns it to the QuoteSize field.
func (o *CreateOrderRequestOrderConfigurationMarketMarketIoc) SetQuoteSize(v string) {
	o.QuoteSize = &v
}

// GetBaseSize returns the BaseSize field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationMarketMarketIoc) GetBaseSize() string {
	if o == nil || isNil(o.BaseSize) {
		var ret string
		return ret
	}
	return *o.BaseSize
}

// GetBaseSizeOk returns a tuple with the BaseSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationMarketMarketIoc) GetBaseSizeOk() (*string, bool) {
	if o == nil || isNil(o.BaseSize) {
    return nil, false
	}
	return o.BaseSize, true
}

// HasBaseSize returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationMarketMarketIoc) HasBaseSize() bool {
	if o != nil && !isNil(o.BaseSize) {
		return true
	}

	return false
}

// SetBaseSize gets a reference to the given string and assigns it to the BaseSize field.
func (o *CreateOrderRequestOrderConfigurationMarketMarketIoc) SetBaseSize(v string) {
	o.BaseSize = &v
}

func (o CreateOrderRequestOrderConfigurationMarketMarketIoc) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.QuoteSize) {
		toSerialize["quote_size"] = o.QuoteSize
	}
	if !isNil(o.BaseSize) {
		toSerialize["base_size"] = o.BaseSize
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrderRequestOrderConfigurationMarketMarketIoc struct {
	value *CreateOrderRequestOrderConfigurationMarketMarketIoc
	isSet bool
}

func (v NullableCreateOrderRequestOrderConfigurationMarketMarketIoc) Get() *CreateOrderRequestOrderConfigurationMarketMarketIoc {
	return v.value
}

func (v *NullableCreateOrderRequestOrderConfigurationMarketMarketIoc) Set(val *CreateOrderRequestOrderConfigurationMarketMarketIoc) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestOrderConfigurationMarketMarketIoc) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestOrderConfigurationMarketMarketIoc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestOrderConfigurationMarketMarketIoc(val *CreateOrderRequestOrderConfigurationMarketMarketIoc) *NullableCreateOrderRequestOrderConfigurationMarketMarketIoc {
	return &NullableCreateOrderRequestOrderConfigurationMarketMarketIoc{value: val, isSet: true}
}

func (v NullableCreateOrderRequestOrderConfigurationMarketMarketIoc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestOrderConfigurationMarketMarketIoc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


