/*
Coinbase Advanced Trading API

OpenAPI 3.x specification for Coinbase Adavanced Trading

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// OutputOrderConfiguration struct for OutputOrderConfiguration
type OutputOrderConfiguration struct {
	MarketMarketIoc *OutputOrderConfigurationMarketMarketIoc `json:"market_market_ioc,omitempty"`
	LimitLimitGtc *OutputOrderConfigurationLimitLimitGtc `json:"limit_limit_gtc,omitempty"`
	LimitLimitGtd *OutputOrderConfigurationLimitLimitGtd `json:"limit_limit_gtd,omitempty"`
	StopLimitStopLimitGtc *OutputOrderConfigurationStopLimitStopLimitGtc `json:"stop_limit_stop_limit_gtc,omitempty"`
	StopLimitStopLimitGtd *OutputOrderConfigurationStopLimitStopLimitGtd `json:"stop_limit_stop_limit_gtd,omitempty"`
}

// NewOutputOrderConfiguration instantiates a new OutputOrderConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputOrderConfiguration() *OutputOrderConfiguration {
	this := OutputOrderConfiguration{}
	return &this
}

// NewOutputOrderConfigurationWithDefaults instantiates a new OutputOrderConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputOrderConfigurationWithDefaults() *OutputOrderConfiguration {
	this := OutputOrderConfiguration{}
	return &this
}

// GetMarketMarketIoc returns the MarketMarketIoc field value if set, zero value otherwise.
func (o *OutputOrderConfiguration) GetMarketMarketIoc() OutputOrderConfigurationMarketMarketIoc {
	if o == nil || isNil(o.MarketMarketIoc) {
		var ret OutputOrderConfigurationMarketMarketIoc
		return ret
	}
	return *o.MarketMarketIoc
}

// GetMarketMarketIocOk returns a tuple with the MarketMarketIoc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputOrderConfiguration) GetMarketMarketIocOk() (*OutputOrderConfigurationMarketMarketIoc, bool) {
	if o == nil || isNil(o.MarketMarketIoc) {
    return nil, false
	}
	return o.MarketMarketIoc, true
}

// HasMarketMarketIoc returns a boolean if a field has been set.
func (o *OutputOrderConfiguration) HasMarketMarketIoc() bool {
	if o != nil && !isNil(o.MarketMarketIoc) {
		return true
	}

	return false
}

// SetMarketMarketIoc gets a reference to the given OutputOrderConfigurationMarketMarketIoc and assigns it to the MarketMarketIoc field.
func (o *OutputOrderConfiguration) SetMarketMarketIoc(v OutputOrderConfigurationMarketMarketIoc) {
	o.MarketMarketIoc = &v
}

// GetLimitLimitGtc returns the LimitLimitGtc field value if set, zero value otherwise.
func (o *OutputOrderConfiguration) GetLimitLimitGtc() OutputOrderConfigurationLimitLimitGtc {
	if o == nil || isNil(o.LimitLimitGtc) {
		var ret OutputOrderConfigurationLimitLimitGtc
		return ret
	}
	return *o.LimitLimitGtc
}

// GetLimitLimitGtcOk returns a tuple with the LimitLimitGtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputOrderConfiguration) GetLimitLimitGtcOk() (*OutputOrderConfigurationLimitLimitGtc, bool) {
	if o == nil || isNil(o.LimitLimitGtc) {
    return nil, false
	}
	return o.LimitLimitGtc, true
}

// HasLimitLimitGtc returns a boolean if a field has been set.
func (o *OutputOrderConfiguration) HasLimitLimitGtc() bool {
	if o != nil && !isNil(o.LimitLimitGtc) {
		return true
	}

	return false
}

// SetLimitLimitGtc gets a reference to the given OutputOrderConfigurationLimitLimitGtc and assigns it to the LimitLimitGtc field.
func (o *OutputOrderConfiguration) SetLimitLimitGtc(v OutputOrderConfigurationLimitLimitGtc) {
	o.LimitLimitGtc = &v
}

// GetLimitLimitGtd returns the LimitLimitGtd field value if set, zero value otherwise.
func (o *OutputOrderConfiguration) GetLimitLimitGtd() OutputOrderConfigurationLimitLimitGtd {
	if o == nil || isNil(o.LimitLimitGtd) {
		var ret OutputOrderConfigurationLimitLimitGtd
		return ret
	}
	return *o.LimitLimitGtd
}

// GetLimitLimitGtdOk returns a tuple with the LimitLimitGtd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputOrderConfiguration) GetLimitLimitGtdOk() (*OutputOrderConfigurationLimitLimitGtd, bool) {
	if o == nil || isNil(o.LimitLimitGtd) {
    return nil, false
	}
	return o.LimitLimitGtd, true
}

// HasLimitLimitGtd returns a boolean if a field has been set.
func (o *OutputOrderConfiguration) HasLimitLimitGtd() bool {
	if o != nil && !isNil(o.LimitLimitGtd) {
		return true
	}

	return false
}

// SetLimitLimitGtd gets a reference to the given OutputOrderConfigurationLimitLimitGtd and assigns it to the LimitLimitGtd field.
func (o *OutputOrderConfiguration) SetLimitLimitGtd(v OutputOrderConfigurationLimitLimitGtd) {
	o.LimitLimitGtd = &v
}

// GetStopLimitStopLimitGtc returns the StopLimitStopLimitGtc field value if set, zero value otherwise.
func (o *OutputOrderConfiguration) GetStopLimitStopLimitGtc() OutputOrderConfigurationStopLimitStopLimitGtc {
	if o == nil || isNil(o.StopLimitStopLimitGtc) {
		var ret OutputOrderConfigurationStopLimitStopLimitGtc
		return ret
	}
	return *o.StopLimitStopLimitGtc
}

// GetStopLimitStopLimitGtcOk returns a tuple with the StopLimitStopLimitGtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputOrderConfiguration) GetStopLimitStopLimitGtcOk() (*OutputOrderConfigurationStopLimitStopLimitGtc, bool) {
	if o == nil || isNil(o.StopLimitStopLimitGtc) {
    return nil, false
	}
	return o.StopLimitStopLimitGtc, true
}

// HasStopLimitStopLimitGtc returns a boolean if a field has been set.
func (o *OutputOrderConfiguration) HasStopLimitStopLimitGtc() bool {
	if o != nil && !isNil(o.StopLimitStopLimitGtc) {
		return true
	}

	return false
}

// SetStopLimitStopLimitGtc gets a reference to the given OutputOrderConfigurationStopLimitStopLimitGtc and assigns it to the StopLimitStopLimitGtc field.
func (o *OutputOrderConfiguration) SetStopLimitStopLimitGtc(v OutputOrderConfigurationStopLimitStopLimitGtc) {
	o.StopLimitStopLimitGtc = &v
}

// GetStopLimitStopLimitGtd returns the StopLimitStopLimitGtd field value if set, zero value otherwise.
func (o *OutputOrderConfiguration) GetStopLimitStopLimitGtd() OutputOrderConfigurationStopLimitStopLimitGtd {
	if o == nil || isNil(o.StopLimitStopLimitGtd) {
		var ret OutputOrderConfigurationStopLimitStopLimitGtd
		return ret
	}
	return *o.StopLimitStopLimitGtd
}

// GetStopLimitStopLimitGtdOk returns a tuple with the StopLimitStopLimitGtd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputOrderConfiguration) GetStopLimitStopLimitGtdOk() (*OutputOrderConfigurationStopLimitStopLimitGtd, bool) {
	if o == nil || isNil(o.StopLimitStopLimitGtd) {
    return nil, false
	}
	return o.StopLimitStopLimitGtd, true
}

// HasStopLimitStopLimitGtd returns a boolean if a field has been set.
func (o *OutputOrderConfiguration) HasStopLimitStopLimitGtd() bool {
	if o != nil && !isNil(o.StopLimitStopLimitGtd) {
		return true
	}

	return false
}

// SetStopLimitStopLimitGtd gets a reference to the given OutputOrderConfigurationStopLimitStopLimitGtd and assigns it to the StopLimitStopLimitGtd field.
func (o *OutputOrderConfiguration) SetStopLimitStopLimitGtd(v OutputOrderConfigurationStopLimitStopLimitGtd) {
	o.StopLimitStopLimitGtd = &v
}

func (o OutputOrderConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.MarketMarketIoc) {
		toSerialize["market_market_ioc"] = o.MarketMarketIoc
	}
	if !isNil(o.LimitLimitGtc) {
		toSerialize["limit_limit_gtc"] = o.LimitLimitGtc
	}
	if !isNil(o.LimitLimitGtd) {
		toSerialize["limit_limit_gtd"] = o.LimitLimitGtd
	}
	if !isNil(o.StopLimitStopLimitGtc) {
		toSerialize["stop_limit_stop_limit_gtc"] = o.StopLimitStopLimitGtc
	}
	if !isNil(o.StopLimitStopLimitGtd) {
		toSerialize["stop_limit_stop_limit_gtd"] = o.StopLimitStopLimitGtd
	}
	return json.Marshal(toSerialize)
}

type NullableOutputOrderConfiguration struct {
	value *OutputOrderConfiguration
	isSet bool
}

func (v NullableOutputOrderConfiguration) Get() *OutputOrderConfiguration {
	return v.value
}

func (v *NullableOutputOrderConfiguration) Set(val *OutputOrderConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputOrderConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputOrderConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputOrderConfiguration(val *OutputOrderConfiguration) *NullableOutputOrderConfiguration {
	return &NullableOutputOrderConfiguration{value: val, isSet: true}
}

func (v NullableOutputOrderConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputOrderConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


