/*
Coinbase Advanced Trading API

OpenAPI 3.x specification for Coinbase Adavanced Trading

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc struct for CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc
type CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc struct {
	BaseSize *string `json:"base_size,omitempty"`
	LimitPrice *string `json:"limit_price,omitempty"`
	StopPrice *string `json:"stop_price,omitempty"`
	StopDirection *string `json:"stop_direction,omitempty"`
}

// NewCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc instantiates a new CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc() *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc {
	this := CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc{}
	return &this
}

// NewCreateOrderRequestOrderConfigurationStopLimitStopLimitGtcWithDefaults instantiates a new CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestOrderConfigurationStopLimitStopLimitGtcWithDefaults() *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc {
	this := CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc{}
	return &this
}

// GetBaseSize returns the BaseSize field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) GetBaseSize() string {
	if o == nil || isNil(o.BaseSize) {
		var ret string
		return ret
	}
	return *o.BaseSize
}

// GetBaseSizeOk returns a tuple with the BaseSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) GetBaseSizeOk() (*string, bool) {
	if o == nil || isNil(o.BaseSize) {
    return nil, false
	}
	return o.BaseSize, true
}

// HasBaseSize returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) HasBaseSize() bool {
	if o != nil && !isNil(o.BaseSize) {
		return true
	}

	return false
}

// SetBaseSize gets a reference to the given string and assigns it to the BaseSize field.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) SetBaseSize(v string) {
	o.BaseSize = &v
}

// GetLimitPrice returns the LimitPrice field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) GetLimitPrice() string {
	if o == nil || isNil(o.LimitPrice) {
		var ret string
		return ret
	}
	return *o.LimitPrice
}

// GetLimitPriceOk returns a tuple with the LimitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) GetLimitPriceOk() (*string, bool) {
	if o == nil || isNil(o.LimitPrice) {
    return nil, false
	}
	return o.LimitPrice, true
}

// HasLimitPrice returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) HasLimitPrice() bool {
	if o != nil && !isNil(o.LimitPrice) {
		return true
	}

	return false
}

// SetLimitPrice gets a reference to the given string and assigns it to the LimitPrice field.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) SetLimitPrice(v string) {
	o.LimitPrice = &v
}

// GetStopPrice returns the StopPrice field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) GetStopPrice() string {
	if o == nil || isNil(o.StopPrice) {
		var ret string
		return ret
	}
	return *o.StopPrice
}

// GetStopPriceOk returns a tuple with the StopPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) GetStopPriceOk() (*string, bool) {
	if o == nil || isNil(o.StopPrice) {
    return nil, false
	}
	return o.StopPrice, true
}

// HasStopPrice returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) HasStopPrice() bool {
	if o != nil && !isNil(o.StopPrice) {
		return true
	}

	return false
}

// SetStopPrice gets a reference to the given string and assigns it to the StopPrice field.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) SetStopPrice(v string) {
	o.StopPrice = &v
}

// GetStopDirection returns the StopDirection field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) GetStopDirection() string {
	if o == nil || isNil(o.StopDirection) {
		var ret string
		return ret
	}
	return *o.StopDirection
}

// GetStopDirectionOk returns a tuple with the StopDirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) GetStopDirectionOk() (*string, bool) {
	if o == nil || isNil(o.StopDirection) {
    return nil, false
	}
	return o.StopDirection, true
}

// HasStopDirection returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) HasStopDirection() bool {
	if o != nil && !isNil(o.StopDirection) {
		return true
	}

	return false
}

// SetStopDirection gets a reference to the given string and assigns it to the StopDirection field.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) SetStopDirection(v string) {
	o.StopDirection = &v
}

func (o CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.BaseSize) {
		toSerialize["base_size"] = o.BaseSize
	}
	if !isNil(o.LimitPrice) {
		toSerialize["limit_price"] = o.LimitPrice
	}
	if !isNil(o.StopPrice) {
		toSerialize["stop_price"] = o.StopPrice
	}
	if !isNil(o.StopDirection) {
		toSerialize["stop_direction"] = o.StopDirection
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc struct {
	value *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc
	isSet bool
}

func (v NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) Get() *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc {
	return v.value
}

func (v *NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) Set(val *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc(val *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) *NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc {
	return &NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc{value: val, isSet: true}
}

func (v NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


