/*
Coinbase Advanced Trading API

OpenAPI 3.x specification for Coinbase Adavanced Trading

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// CreateOrderRequestOrderConfiguration struct for CreateOrderRequestOrderConfiguration
type CreateOrderRequestOrderConfiguration struct {
	MarketMarketIoc *CreateOrderRequestOrderConfigurationMarketMarketIoc `json:"market_market_ioc,omitempty"`
	LimitLimitGtc *CreateOrderRequestOrderConfigurationLimitLimitGtc `json:"limit_limit_gtc,omitempty"`
	LimitLimitGtd *CreateOrderRequestOrderConfigurationLimitLimitGtd `json:"limit_limit_gtd,omitempty"`
	StopLimitStopLimitGtc *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc `json:"stop_limit_stop_limit_gtc,omitempty"`
	StopLimitStopLimitGtd *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd `json:"stop_limit_stop_limit_gtd,omitempty"`
}

// NewCreateOrderRequestOrderConfiguration instantiates a new CreateOrderRequestOrderConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestOrderConfiguration() *CreateOrderRequestOrderConfiguration {
	this := CreateOrderRequestOrderConfiguration{}
	return &this
}

// NewCreateOrderRequestOrderConfigurationWithDefaults instantiates a new CreateOrderRequestOrderConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestOrderConfigurationWithDefaults() *CreateOrderRequestOrderConfiguration {
	this := CreateOrderRequestOrderConfiguration{}
	return &this
}

// GetMarketMarketIoc returns the MarketMarketIoc field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfiguration) GetMarketMarketIoc() CreateOrderRequestOrderConfigurationMarketMarketIoc {
	if o == nil || isNil(o.MarketMarketIoc) {
		var ret CreateOrderRequestOrderConfigurationMarketMarketIoc
		return ret
	}
	return *o.MarketMarketIoc
}

// GetMarketMarketIocOk returns a tuple with the MarketMarketIoc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfiguration) GetMarketMarketIocOk() (*CreateOrderRequestOrderConfigurationMarketMarketIoc, bool) {
	if o == nil || isNil(o.MarketMarketIoc) {
    return nil, false
	}
	return o.MarketMarketIoc, true
}

// HasMarketMarketIoc returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfiguration) HasMarketMarketIoc() bool {
	if o != nil && !isNil(o.MarketMarketIoc) {
		return true
	}

	return false
}

// SetMarketMarketIoc gets a reference to the given CreateOrderRequestOrderConfigurationMarketMarketIoc and assigns it to the MarketMarketIoc field.
func (o *CreateOrderRequestOrderConfiguration) SetMarketMarketIoc(v CreateOrderRequestOrderConfigurationMarketMarketIoc) {
	o.MarketMarketIoc = &v
}

// GetLimitLimitGtc returns the LimitLimitGtc field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfiguration) GetLimitLimitGtc() CreateOrderRequestOrderConfigurationLimitLimitGtc {
	if o == nil || isNil(o.LimitLimitGtc) {
		var ret CreateOrderRequestOrderConfigurationLimitLimitGtc
		return ret
	}
	return *o.LimitLimitGtc
}

// GetLimitLimitGtcOk returns a tuple with the LimitLimitGtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfiguration) GetLimitLimitGtcOk() (*CreateOrderRequestOrderConfigurationLimitLimitGtc, bool) {
	if o == nil || isNil(o.LimitLimitGtc) {
    return nil, false
	}
	return o.LimitLimitGtc, true
}

// HasLimitLimitGtc returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfiguration) HasLimitLimitGtc() bool {
	if o != nil && !isNil(o.LimitLimitGtc) {
		return true
	}

	return false
}

// SetLimitLimitGtc gets a reference to the given CreateOrderRequestOrderConfigurationLimitLimitGtc and assigns it to the LimitLimitGtc field.
func (o *CreateOrderRequestOrderConfiguration) SetLimitLimitGtc(v CreateOrderRequestOrderConfigurationLimitLimitGtc) {
	o.LimitLimitGtc = &v
}

// GetLimitLimitGtd returns the LimitLimitGtd field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfiguration) GetLimitLimitGtd() CreateOrderRequestOrderConfigurationLimitLimitGtd {
	if o == nil || isNil(o.LimitLimitGtd) {
		var ret CreateOrderRequestOrderConfigurationLimitLimitGtd
		return ret
	}
	return *o.LimitLimitGtd
}

// GetLimitLimitGtdOk returns a tuple with the LimitLimitGtd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfiguration) GetLimitLimitGtdOk() (*CreateOrderRequestOrderConfigurationLimitLimitGtd, bool) {
	if o == nil || isNil(o.LimitLimitGtd) {
    return nil, false
	}
	return o.LimitLimitGtd, true
}

// HasLimitLimitGtd returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfiguration) HasLimitLimitGtd() bool {
	if o != nil && !isNil(o.LimitLimitGtd) {
		return true
	}

	return false
}

// SetLimitLimitGtd gets a reference to the given CreateOrderRequestOrderConfigurationLimitLimitGtd and assigns it to the LimitLimitGtd field.
func (o *CreateOrderRequestOrderConfiguration) SetLimitLimitGtd(v CreateOrderRequestOrderConfigurationLimitLimitGtd) {
	o.LimitLimitGtd = &v
}

// GetStopLimitStopLimitGtc returns the StopLimitStopLimitGtc field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfiguration) GetStopLimitStopLimitGtc() CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc {
	if o == nil || isNil(o.StopLimitStopLimitGtc) {
		var ret CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc
		return ret
	}
	return *o.StopLimitStopLimitGtc
}

// GetStopLimitStopLimitGtcOk returns a tuple with the StopLimitStopLimitGtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfiguration) GetStopLimitStopLimitGtcOk() (*CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc, bool) {
	if o == nil || isNil(o.StopLimitStopLimitGtc) {
    return nil, false
	}
	return o.StopLimitStopLimitGtc, true
}

// HasStopLimitStopLimitGtc returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfiguration) HasStopLimitStopLimitGtc() bool {
	if o != nil && !isNil(o.StopLimitStopLimitGtc) {
		return true
	}

	return false
}

// SetStopLimitStopLimitGtc gets a reference to the given CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc and assigns it to the StopLimitStopLimitGtc field.
func (o *CreateOrderRequestOrderConfiguration) SetStopLimitStopLimitGtc(v CreateOrderRequestOrderConfigurationStopLimitStopLimitGtc) {
	o.StopLimitStopLimitGtc = &v
}

// GetStopLimitStopLimitGtd returns the StopLimitStopLimitGtd field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfiguration) GetStopLimitStopLimitGtd() CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd {
	if o == nil || isNil(o.StopLimitStopLimitGtd) {
		var ret CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd
		return ret
	}
	return *o.StopLimitStopLimitGtd
}

// GetStopLimitStopLimitGtdOk returns a tuple with the StopLimitStopLimitGtd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfiguration) GetStopLimitStopLimitGtdOk() (*CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd, bool) {
	if o == nil || isNil(o.StopLimitStopLimitGtd) {
    return nil, false
	}
	return o.StopLimitStopLimitGtd, true
}

// HasStopLimitStopLimitGtd returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfiguration) HasStopLimitStopLimitGtd() bool {
	if o != nil && !isNil(o.StopLimitStopLimitGtd) {
		return true
	}

	return false
}

// SetStopLimitStopLimitGtd gets a reference to the given CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd and assigns it to the StopLimitStopLimitGtd field.
func (o *CreateOrderRequestOrderConfiguration) SetStopLimitStopLimitGtd(v CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) {
	o.StopLimitStopLimitGtd = &v
}

func (o CreateOrderRequestOrderConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.MarketMarketIoc) {
		toSerialize["market_market_ioc"] = o.MarketMarketIoc
	}
	if !isNil(o.LimitLimitGtc) {
		toSerialize["limit_limit_gtc"] = o.LimitLimitGtc
	}
	if !isNil(o.LimitLimitGtd) {
		toSerialize["limit_limit_gtd"] = o.LimitLimitGtd
	}
	if !isNil(o.StopLimitStopLimitGtc) {
		toSerialize["stop_limit_stop_limit_gtc"] = o.StopLimitStopLimitGtc
	}
	if !isNil(o.StopLimitStopLimitGtd) {
		toSerialize["stop_limit_stop_limit_gtd"] = o.StopLimitStopLimitGtd
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrderRequestOrderConfiguration struct {
	value *CreateOrderRequestOrderConfiguration
	isSet bool
}

func (v NullableCreateOrderRequestOrderConfiguration) Get() *CreateOrderRequestOrderConfiguration {
	return v.value
}

func (v *NullableCreateOrderRequestOrderConfiguration) Set(val *CreateOrderRequestOrderConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestOrderConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestOrderConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestOrderConfiguration(val *CreateOrderRequestOrderConfiguration) *NullableCreateOrderRequestOrderConfiguration {
	return &NullableCreateOrderRequestOrderConfiguration{value: val, isSet: true}
}

func (v NullableCreateOrderRequestOrderConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestOrderConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


