/*
Coinbase Advanced Trading API

OpenAPI 3.x specification for Coinbase Adavanced Trading

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// CreateOrderRequestOrderConfigurationLimitLimitGtc struct for CreateOrderRequestOrderConfigurationLimitLimitGtc
type CreateOrderRequestOrderConfigurationLimitLimitGtc struct {
	BaseSize *string `json:"base_size,omitempty"`
	LimitPrice *string `json:"limit_price,omitempty"`
	PostOnly *bool `json:"post_only,omitempty"`
}

// NewCreateOrderRequestOrderConfigurationLimitLimitGtc instantiates a new CreateOrderRequestOrderConfigurationLimitLimitGtc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestOrderConfigurationLimitLimitGtc() *CreateOrderRequestOrderConfigurationLimitLimitGtc {
	this := CreateOrderRequestOrderConfigurationLimitLimitGtc{}
	return &this
}

// NewCreateOrderRequestOrderConfigurationLimitLimitGtcWithDefaults instantiates a new CreateOrderRequestOrderConfigurationLimitLimitGtc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestOrderConfigurationLimitLimitGtcWithDefaults() *CreateOrderRequestOrderConfigurationLimitLimitGtc {
	this := CreateOrderRequestOrderConfigurationLimitLimitGtc{}
	return &this
}

// GetBaseSize returns the BaseSize field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) GetBaseSize() string {
	if o == nil || isNil(o.BaseSize) {
		var ret string
		return ret
	}
	return *o.BaseSize
}

// GetBaseSizeOk returns a tuple with the BaseSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) GetBaseSizeOk() (*string, bool) {
	if o == nil || isNil(o.BaseSize) {
    return nil, false
	}
	return o.BaseSize, true
}

// HasBaseSize returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) HasBaseSize() bool {
	if o != nil && !isNil(o.BaseSize) {
		return true
	}

	return false
}

// SetBaseSize gets a reference to the given string and assigns it to the BaseSize field.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) SetBaseSize(v string) {
	o.BaseSize = &v
}

// GetLimitPrice returns the LimitPrice field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) GetLimitPrice() string {
	if o == nil || isNil(o.LimitPrice) {
		var ret string
		return ret
	}
	return *o.LimitPrice
}

// GetLimitPriceOk returns a tuple with the LimitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) GetLimitPriceOk() (*string, bool) {
	if o == nil || isNil(o.LimitPrice) {
    return nil, false
	}
	return o.LimitPrice, true
}

// HasLimitPrice returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) HasLimitPrice() bool {
	if o != nil && !isNil(o.LimitPrice) {
		return true
	}

	return false
}

// SetLimitPrice gets a reference to the given string and assigns it to the LimitPrice field.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) SetLimitPrice(v string) {
	o.LimitPrice = &v
}

// GetPostOnly returns the PostOnly field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) GetPostOnly() bool {
	if o == nil || isNil(o.PostOnly) {
		var ret bool
		return ret
	}
	return *o.PostOnly
}

// GetPostOnlyOk returns a tuple with the PostOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) GetPostOnlyOk() (*bool, bool) {
	if o == nil || isNil(o.PostOnly) {
    return nil, false
	}
	return o.PostOnly, true
}

// HasPostOnly returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) HasPostOnly() bool {
	if o != nil && !isNil(o.PostOnly) {
		return true
	}

	return false
}

// SetPostOnly gets a reference to the given bool and assigns it to the PostOnly field.
func (o *CreateOrderRequestOrderConfigurationLimitLimitGtc) SetPostOnly(v bool) {
	o.PostOnly = &v
}

func (o CreateOrderRequestOrderConfigurationLimitLimitGtc) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.BaseSize) {
		toSerialize["base_size"] = o.BaseSize
	}
	if !isNil(o.LimitPrice) {
		toSerialize["limit_price"] = o.LimitPrice
	}
	if !isNil(o.PostOnly) {
		toSerialize["post_only"] = o.PostOnly
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrderRequestOrderConfigurationLimitLimitGtc struct {
	value *CreateOrderRequestOrderConfigurationLimitLimitGtc
	isSet bool
}

func (v NullableCreateOrderRequestOrderConfigurationLimitLimitGtc) Get() *CreateOrderRequestOrderConfigurationLimitLimitGtc {
	return v.value
}

func (v *NullableCreateOrderRequestOrderConfigurationLimitLimitGtc) Set(val *CreateOrderRequestOrderConfigurationLimitLimitGtc) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestOrderConfigurationLimitLimitGtc) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestOrderConfigurationLimitLimitGtc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestOrderConfigurationLimitLimitGtc(val *CreateOrderRequestOrderConfigurationLimitLimitGtc) *NullableCreateOrderRequestOrderConfigurationLimitLimitGtc {
	return &NullableCreateOrderRequestOrderConfigurationLimitLimitGtc{value: val, isSet: true}
}

func (v NullableCreateOrderRequestOrderConfigurationLimitLimitGtc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestOrderConfigurationLimitLimitGtc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


