/*
Coinbase Advanced Trading API

OpenAPI 3.x specification for Coinbase Adavanced Trading

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd struct for CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd
type CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd struct {
	BaseSize *string `json:"base_size,omitempty"`
	LimitPrice *string `json:"limit_price,omitempty"`
	StopPrice *string `json:"stop_price,omitempty"`
	EndTime *string `json:"end_time,omitempty"`
	StopDirection *string `json:"stop_direction,omitempty"`
}

// NewCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd instantiates a new CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd() *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd {
	this := CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd{}
	return &this
}

// NewCreateOrderRequestOrderConfigurationStopLimitStopLimitGtdWithDefaults instantiates a new CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestOrderConfigurationStopLimitStopLimitGtdWithDefaults() *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd {
	this := CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd{}
	return &this
}

// GetBaseSize returns the BaseSize field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) GetBaseSize() string {
	if o == nil || isNil(o.BaseSize) {
		var ret string
		return ret
	}
	return *o.BaseSize
}

// GetBaseSizeOk returns a tuple with the BaseSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) GetBaseSizeOk() (*string, bool) {
	if o == nil || isNil(o.BaseSize) {
    return nil, false
	}
	return o.BaseSize, true
}

// HasBaseSize returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) HasBaseSize() bool {
	if o != nil && !isNil(o.BaseSize) {
		return true
	}

	return false
}

// SetBaseSize gets a reference to the given string and assigns it to the BaseSize field.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) SetBaseSize(v string) {
	o.BaseSize = &v
}

// GetLimitPrice returns the LimitPrice field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) GetLimitPrice() string {
	if o == nil || isNil(o.LimitPrice) {
		var ret string
		return ret
	}
	return *o.LimitPrice
}

// GetLimitPriceOk returns a tuple with the LimitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) GetLimitPriceOk() (*string, bool) {
	if o == nil || isNil(o.LimitPrice) {
    return nil, false
	}
	return o.LimitPrice, true
}

// HasLimitPrice returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) HasLimitPrice() bool {
	if o != nil && !isNil(o.LimitPrice) {
		return true
	}

	return false
}

// SetLimitPrice gets a reference to the given string and assigns it to the LimitPrice field.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) SetLimitPrice(v string) {
	o.LimitPrice = &v
}

// GetStopPrice returns the StopPrice field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) GetStopPrice() string {
	if o == nil || isNil(o.StopPrice) {
		var ret string
		return ret
	}
	return *o.StopPrice
}

// GetStopPriceOk returns a tuple with the StopPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) GetStopPriceOk() (*string, bool) {
	if o == nil || isNil(o.StopPrice) {
    return nil, false
	}
	return o.StopPrice, true
}

// HasStopPrice returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) HasStopPrice() bool {
	if o != nil && !isNil(o.StopPrice) {
		return true
	}

	return false
}

// SetStopPrice gets a reference to the given string and assigns it to the StopPrice field.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) SetStopPrice(v string) {
	o.StopPrice = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) GetEndTime() string {
	if o == nil || isNil(o.EndTime) {
		var ret string
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) GetEndTimeOk() (*string, bool) {
	if o == nil || isNil(o.EndTime) {
    return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) HasEndTime() bool {
	if o != nil && !isNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given string and assigns it to the EndTime field.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) SetEndTime(v string) {
	o.EndTime = &v
}

// GetStopDirection returns the StopDirection field value if set, zero value otherwise.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) GetStopDirection() string {
	if o == nil || isNil(o.StopDirection) {
		var ret string
		return ret
	}
	return *o.StopDirection
}

// GetStopDirectionOk returns a tuple with the StopDirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) GetStopDirectionOk() (*string, bool) {
	if o == nil || isNil(o.StopDirection) {
    return nil, false
	}
	return o.StopDirection, true
}

// HasStopDirection returns a boolean if a field has been set.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) HasStopDirection() bool {
	if o != nil && !isNil(o.StopDirection) {
		return true
	}

	return false
}

// SetStopDirection gets a reference to the given string and assigns it to the StopDirection field.
func (o *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) SetStopDirection(v string) {
	o.StopDirection = &v
}

func (o CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.BaseSize) {
		toSerialize["base_size"] = o.BaseSize
	}
	if !isNil(o.LimitPrice) {
		toSerialize["limit_price"] = o.LimitPrice
	}
	if !isNil(o.StopPrice) {
		toSerialize["stop_price"] = o.StopPrice
	}
	if !isNil(o.EndTime) {
		toSerialize["end_time"] = o.EndTime
	}
	if !isNil(o.StopDirection) {
		toSerialize["stop_direction"] = o.StopDirection
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd struct {
	value *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd
	isSet bool
}

func (v NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) Get() *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd {
	return v.value
}

func (v *NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) Set(val *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd(val *CreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) *NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd {
	return &NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd{value: val, isSet: true}
}

func (v NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestOrderConfigurationStopLimitStopLimitGtd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


